- hosts: localhost
  tasks:
    - name: Remove old container
      shell: docker rm -f feedback-app || true

    - name: Run new container
      shell: docker run -d -p 5000:5000 --name feedback-app feedback-app